// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6XnB5jv9loZf6mTTYghFPIcIDNnW7g3o',
    appId: '1:388082198829:web:080b0e26e2b1a3fd76cba4',
    messagingSenderId: '388082198829',
    projectId: 'gestorfy-app',
    authDomain: 'gestorfy-app.firebaseapp.com',
    storageBucket: 'gestorfy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuk5FeWNQlN5qqj8PIwwcPJWtg49KxdFE',
    appId: '1:388082198829:android:8988c83f6892518976cba4',
    messagingSenderId: '388082198829',
    projectId: 'gestorfy-app',
    storageBucket: 'gestorfy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUVxSYxCoFy3w0hAY4T8zGQsUX_HkMOXI',
    appId: '1:388082198829:ios:90880ae09d4c3f9c76cba4',
    messagingSenderId: '388082198829',
    projectId: 'gestorfy-app',
    storageBucket: 'gestorfy-app.firebasestorage.app',
    iosBundleId: 'com.example.gestorfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUVxSYxCoFy3w0hAY4T8zGQsUX_HkMOXI',
    appId: '1:388082198829:ios:90880ae09d4c3f9c76cba4',
    messagingSenderId: '388082198829',
    projectId: 'gestorfy-app',
    storageBucket: 'gestorfy-app.firebasestorage.app',
    iosBundleId: 'com.example.gestorfy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6XnB5jv9loZf6mTTYghFPIcIDNnW7g3o',
    appId: '1:388082198829:web:b08380495ada9f1a76cba4',
    messagingSenderId: '388082198829',
    projectId: 'gestorfy-app',
    authDomain: 'gestorfy-app.firebaseapp.com',
    storageBucket: 'gestorfy-app.firebasestorage.app',
  );
}
